name: Documentation
on:
  push:
    branches: ['main']
    paths: ['packages/**']
  workflow_dispatch:
jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    if: github.repository_owner == 'thenorthsolution'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Build Docs
        run: npm run docs

      - name: Checkout docs branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: 'out'

      - name: Move docs to correct directory
        run: |
          cp -R docs/* out

      - name: Commit and push
        run: |
          cd out
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Docs build for ${GITHUB_REF_TYPE} ${GITHUB_REF_NAME}: ${GITHUB_SHA}" || true
          git push